apiVersion: v1
kind: Pod
metadata:
    name: nodejs-labeled-02
    labels: 
     env: prod
spec:
    containers:
     - image: enricovittorini/nodejs:1
       name: nodejs
       ports:
       - containerPort: 8080
         protocol: TCP
    nodeSelector:
     ssd: "true"