apiVersion: v1
kind: Pod
metadata:
    name: nodejs-labeled
    labels: 
     env: prod
     creation: manual
spec:
    containers:
     - image: enricovittorini/nodejs:1
       name: nodejs
       ports:
       - containerPort: 8080
         protocol: TCP