apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
 name: nodejs-rs
spec:
 replicas: 3
 selector:
  matchLabels:
   env: prod
 template:
  metadata:
   labels:
    env: prod
  spec:
   containers: 
    - image: enricovittorini/nodejs:1
      name: nodejs-pod
      ports:
      - containerPort: 8080
        protocol: TCP