apiVersion: v1
kind: Pod
metadata:
    name: nodejs-node-ssd
    labels: 
     env: prod
     creation: manual
spec:
    nodeSelector:
     ssd: 'true'
    containers:
     - image: enricovittorini/nodejs:1
       name: nodejs
       ports:
       - containerPort: 8080
         protocol: TCP