apiVersion: v1
kind: Pod
metadata:
    name: nodejs-pbr
spec:
    containers:
     - image: enricovittorini/nodejs_failure:1
       name: nodejs-prb
       livenessProbe:
          httpGet:
           path: /
           port: 8080           
       ports:
       - containerPort: 8080
         protocol: TCP     